kind: ConfigMap
apiVersion: v1
metadata:
  name: gogs-config
  namespace: gogs
  labels:
    name: gogs
data:
  app.ini: |
    RUN_MODE = prod
    RUN_USER = gogs

    [database]
    DB_TYPE  = postgres
    HOST     = postgres:5432
    NAME     = gogs
    USER     = gogs
    PASSWD   = gogs

    [repository]
    ROOT = /opt/gogs/data/repositories

    [server]
    ROOT_URL=http://gogs.2886795314-80-host20nc.environments.katacoda.com
    SSH_DOMAIN=gogs.2886795314-80-host20nc.environments.katacoda.com

    [security]
    INSTALL_LOCK = true

    [service]
    ENABLE_CAPTCHA = false

    [webhook]
    SKIP_TLS_VERIFY = false
