kind: Deployment
apiVersion: apps/v1
metadata:
  name: gogs
  namespace: gogs
  labels:
    name: gogs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gogs
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: gogs
    spec:
      volumes:
        - name: gogs-data
#          persistentVolumeClaim:
#/            claimName: gogs
        - name: gogs-config
          configMap:
            name: gogs-config
            items:
              - key: app.ini
                path: app.ini
            defaultMode: 420
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: gogs
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: gogs-data
              mountPath: /opt/gogs/data
            - name: gogs-config
              mountPath: /etc/gogs/conf
          terminationMessagePolicy: File
          image: 'quay.io/mavazque/gogs:0.11.91'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
